//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WTAnalyzer.Resx {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WTAnalyzer.Resx.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ±1.0 BR.
        /// </summary>
        internal static string _10BR {
            get {
                return ResourceManager.GetString("_10BR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на About.
        /// </summary>
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на About app.
        /// </summary>
        internal static string AboutApp {
            get {
                return ResourceManager.GetString("AboutApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на App for checkout of player statistics.
        /// </summary>
        internal static string AppForCheckoutOfPlayerStatistics {
            get {
                return ResourceManager.GetString("AppForCheckoutOfPlayerStatistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на App for vehicles comparison.
        /// </summary>
        internal static string AppForVehiclesComparison {
            get {
                return ResourceManager.GetString("AppForVehiclesComparison", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ascending.
        /// </summary>
        internal static string Ascending {
            get {
                return ResourceManager.GetString("Ascending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ATGM Count.
        /// </summary>
        internal static string ATGMCount {
            get {
                return ResourceManager.GetString("ATGMCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ATGM Range.
        /// </summary>
        internal static string ATGMRange {
            get {
                return ResourceManager.GetString("ATGMRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Attacker.
        /// </summary>
        internal static string Attacker {
            get {
                return ResourceManager.GetString("Attacker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Attack Helicopter.
        /// </summary>
        internal static string AttackHelicopter {
            get {
                return ResourceManager.GetString("AttackHelicopter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Aviation.
        /// </summary>
        internal static string Aviation {
            get {
                return ResourceManager.GetString("Aviation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Battleship.
        /// </summary>
        internal static string Battleship {
            get {
                return ResourceManager.GetString("Battleship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Better than you.
        /// </summary>
        internal static string BetterThanYou {
            get {
                return ResourceManager.GetString("BetterThanYou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Bomber.
        /// </summary>
        internal static string Bomber {
            get {
                return ResourceManager.GetString("Bomber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Bomb Load.
        /// </summary>
        internal static string BombLoad {
            get {
                return ResourceManager.GetString("BombLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на BR Changer.
        /// </summary>
        internal static string BRChanger {
            get {
                return ResourceManager.GetString("BRChanger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Britain.
        /// </summary>
        internal static string Britain {
            get {
                return ResourceManager.GetString("Britain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Burst Mass.
        /// </summary>
        internal static string BurstMass {
            get {
                return ResourceManager.GetString("BurstMass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Check Internet connection.
        /// </summary>
        internal static string CheckInternetConnection {
            get {
                return ResourceManager.GetString("CheckInternetConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Check this cool app for War Thunder.
        /// </summary>
        internal static string CheckThisCoolApp {
            get {
                return ResourceManager.GetString("CheckThisCoolApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на China.
        /// </summary>
        internal static string China {
            get {
                return ResourceManager.GetString("China", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Circulation time.
        /// </summary>
        internal static string CirculationTime {
            get {
                return ResourceManager.GetString("CirculationTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Climb time (0-5000 m).
        /// </summary>
        internal static string Climb {
            get {
                return ResourceManager.GetString("Climb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Climb time (0-1000 m).
        /// </summary>
        internal static string ClimbTime01000M {
            get {
                return ResourceManager.GetString("ClimbTime01000M", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Count of Vehicles per Type.
        /// </summary>
        internal static string CountOfVehiclePerType {
            get {
                return ResourceManager.GetString("CountOfVehiclePerType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Count of Vehicles per Year.
        /// </summary>
        internal static string CountOfVehiclePerYear {
            get {
                return ResourceManager.GetString("CountOfVehiclePerYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Crew count.
        /// </summary>
        internal static string CrewCount {
            get {
                return ResourceManager.GetString("CrewCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cruiser.
        /// </summary>
        internal static string Cruiser {
            get {
                return ResourceManager.GetString("Cruiser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Descending.
        /// </summary>
        internal static string Descending {
            get {
                return ResourceManager.GetString("Descending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Destroyer.
        /// </summary>
        internal static string Destroyer {
            get {
                return ResourceManager.GetString("Destroyer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Displacement.
        /// </summary>
        internal static string Displacement {
            get {
                return ResourceManager.GetString("Displacement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Download helicopters data.
        /// </summary>
        internal static string DownloadHelicoptersData {
            get {
                return ResourceManager.GetString("DownloadHelicoptersData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Download plane data.
        /// </summary>
        internal static string DownloadPlaneData {
            get {
                return ResourceManager.GetString("DownloadPlaneData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Download ships data.
        /// </summary>
        internal static string DownloadShipsData {
            get {
                return ResourceManager.GetString("DownloadShipsData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Download tanks data.
        /// </summary>
        internal static string DownloadTanksData {
            get {
                return ResourceManager.GetString("DownloadTanksData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Engine Power.
        /// </summary>
        internal static string EnginePower {
            get {
                return ResourceManager.GetString("EnginePower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Explore.
        /// </summary>
        internal static string Explorer {
            get {
                return ResourceManager.GetString("Explorer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Feedback.
        /// </summary>
        internal static string Feedback {
            get {
                return ResourceManager.GetString("Feedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Fighter.
        /// </summary>
        internal static string Fighter {
            get {
                return ResourceManager.GetString("Fighter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на First fly Year.
        /// </summary>
        internal static string FirstFlyYear {
            get {
                return ResourceManager.GetString("FirstFlyYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на First ride year.
        /// </summary>
        internal static string FirstRideYear {
            get {
                return ResourceManager.GetString("FirstRideYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Flutter.
        /// </summary>
        internal static string Flutter {
            get {
                return ResourceManager.GetString("Flutter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Follow the news.
        /// </summary>
        internal static string FollowTheNews {
            get {
                return ResourceManager.GetString("FollowTheNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Follow the news, make suggest.
        /// </summary>
        internal static string FollowTheNewsAskQuestion {
            get {
                return ResourceManager.GetString("FollowTheNewsAskQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Force DB Update.
        /// </summary>
        internal static string ForceDBUpdate {
            get {
                return ResourceManager.GetString("ForceDBUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на France.
        /// </summary>
        internal static string France {
            get {
                return ResourceManager.GetString("France", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Germany.
        /// </summary>
        internal static string Germany {
            get {
                return ResourceManager.GetString("Germany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Heavy Tank.
        /// </summary>
        internal static string HeavyTank {
            get {
                return ResourceManager.GetString("HeavyTank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Helicopters.
        /// </summary>
        internal static string Helicopters {
            get {
                return ResourceManager.GetString("Helicopters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Hints.
        /// </summary>
        internal static string Hints {
            get {
                return ResourceManager.GetString("Hints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на h.p.
        /// </summary>
        internal static string HP {
            get {
                return ResourceManager.GetString("HP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Hull armor.
        /// </summary>
        internal static string HullArmor {
            get {
                return ResourceManager.GetString("HullArmor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Italy.
        /// </summary>
        internal static string Italy {
            get {
                return ResourceManager.GetString("Italy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на item.
        /// </summary>
        internal static string Item {
            get {
                return ResourceManager.GetString("Item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Japan.
        /// </summary>
        internal static string Japan {
            get {
                return ResourceManager.GetString("Japan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на kg.
        /// </summary>
        internal static string Kg {
            get {
                return ResourceManager.GetString("Kg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на kg/s.
        /// </summary>
        internal static string KgS {
            get {
                return ResourceManager.GetString("KgS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на km/h.
        /// </summary>
        internal static string KmH {
            get {
                return ResourceManager.GetString("KmH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Launched year.
        /// </summary>
        internal static string LaunchedYear {
            get {
                return ResourceManager.GetString("LaunchedYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Light Tank.
        /// </summary>
        internal static string LightTank {
            get {
                return ResourceManager.GetString("LightTank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Loading vehicle data. This may take up to a 15 sec.
        /// </summary>
        internal static string LoadingVehicleData {
            get {
                return ResourceManager.GetString("LoadingVehicleData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Lower armor plate.
        /// </summary>
        internal static string LowerArmorPlate {
            get {
                return ResourceManager.GetString("LowerArmorPlate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на m.
        /// </summary>
        internal static string M {
            get {
                return ResourceManager.GetString("M", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Main caliber reload.
        /// </summary>
        internal static string MainCaliberReload {
            get {
                return ResourceManager.GetString("MainCaliberReload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Main caliber size.
        /// </summary>
        internal static string MainCaliberSize {
            get {
                return ResourceManager.GetString("MainCaliberSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Speed at 0 m.
        /// </summary>
        internal static string MaxSpeed {
            get {
                return ResourceManager.GetString("MaxSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Speed at 5000 m.
        /// </summary>
        internal static string MaxSpeedAt5000M {
            get {
                return ResourceManager.GetString("MaxSpeedAt5000M", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Max speed.
        /// </summary>
        internal static string MaxSpeedShip {
            get {
                return ResourceManager.GetString("MaxSpeedShip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Medium Tank.
        /// </summary>
        internal static string MediumTank {
            get {
                return ResourceManager.GetString("MediumTank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на mm.
        /// </summary>
        internal static string Mm {
            get {
                return ResourceManager.GetString("Mm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Nations.
        /// </summary>
        internal static string Nations {
            get {
                return ResourceManager.GetString("Nations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на No internet.
        /// </summary>
        internal static string NoInternet {
            get {
                return ResourceManager.GetString("NoInternet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Optimal Alitude.
        /// </summary>
        internal static string OptimalAlitude {
            get {
                return ResourceManager.GetString("OptimalAlitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Order.
        /// </summary>
        internal static string Order {
            get {
                return ResourceManager.GetString("Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Overall.
        /// </summary>
        internal static string Overall {
            get {
                return ResourceManager.GetString("Overall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Penetration.
        /// </summary>
        internal static string Penetration {
            get {
                return ResourceManager.GetString("Penetration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Please make sure the Internet is available.
        /// </summary>
        internal static string PleaseMakeSure {
            get {
                return ResourceManager.GetString("PleaseMakeSure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Premium.
        /// </summary>
        internal static string Premium {
            get {
                return ResourceManager.GetString("Premium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Privacy policy.
        /// </summary>
        internal static string PrivacyPolicy {
            get {
                return ResourceManager.GetString("PrivacyPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Promotional.
        /// </summary>
        internal static string Promotional {
            get {
                return ResourceManager.GetString("Promotional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Property.
        /// </summary>
        internal static string Property {
            get {
                return ResourceManager.GetString("Property", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Quit.
        /// </summary>
        internal static string Quit {
            get {
                return ResourceManager.GetString("Quit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ranks.
        /// </summary>
        internal static string Ranks {
            get {
                return ResourceManager.GetString("Ranks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Rate the app.
        /// </summary>
        internal static string RateTheApp {
            get {
                return ResourceManager.GetString("RateTheApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Rate us in store:.
        /// </summary>
        internal static string RateUsInStore {
            get {
                return ResourceManager.GetString("RateUsInStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Reload time.
        /// </summary>
        internal static string ReloadTime {
            get {
                return ResourceManager.GetString("ReloadTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Repair Cost.
        /// </summary>
        internal static string RepairCost {
            get {
                return ResourceManager.GetString("RepairCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Report a bug.
        /// </summary>
        internal static string ReportABug {
            get {
                return ResourceManager.GetString("ReportABug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на RESET.
        /// </summary>
        internal static string RESET {
            get {
                return ResourceManager.GetString("RESET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Reverse speed.
        /// </summary>
        internal static string ReverseSpeed {
            get {
                return ResourceManager.GetString("ReverseSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Role of vehicles per class.
        /// </summary>
        internal static string RoleOfVehiclesPerClass {
            get {
                return ResourceManager.GetString("RoleOfVehiclesPerClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Roles.
        /// </summary>
        internal static string Roles {
            get {
                return ResourceManager.GetString("Roles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на s.
        /// </summary>
        internal static string S {
            get {
                return ResourceManager.GetString("S", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Share with friends.
        /// </summary>
        internal static string ShareWithFriends {
            get {
                return ResourceManager.GetString("ShareWithFriends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Destroyer.
        /// </summary>
        internal static string ShipDestroyer {
            get {
                return ResourceManager.GetString("ShipDestroyer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Fleet.
        /// </summary>
        internal static string Ships {
            get {
                return ResourceManager.GetString("Ships", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на s.l.
        /// </summary>
        internal static string SL {
            get {
                return ResourceManager.GetString("SL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на SPAA.
        /// </summary>
        internal static string SPAA {
            get {
                return ResourceManager.GetString("SPAA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Speed at road.
        /// </summary>
        internal static string SpeedAtRoad {
            get {
                return ResourceManager.GetString("SpeedAtRoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Speed at sea level.
        /// </summary>
        internal static string SpeedAtSeaLevel {
            get {
                return ResourceManager.GetString("SpeedAtSeaLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Speed at terrain.
        /// </summary>
        internal static string SpeedAtTerrain {
            get {
                return ResourceManager.GetString("SpeedAtTerrain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Squadron.
        /// </summary>
        internal static string Squadron {
            get {
                return ResourceManager.GetString("Squadron", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на SUBMIT.
        /// </summary>
        internal static string SUBMIT {
            get {
                return ResourceManager.GetString("SUBMIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Support us on Patreon.
        /// </summary>
        internal static string SupportUsOnPatreon {
            get {
                return ResourceManager.GetString("SupportUsOnPatreon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Sweden.
        /// </summary>
        internal static string Sweden {
            get {
                return ResourceManager.GetString("Sweden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на t.
        /// </summary>
        internal static string T {
            get {
                return ResourceManager.GetString("T", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Tanks.
        /// </summary>
        internal static string Tanks {
            get {
                return ResourceManager.GetString("Tanks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The database contains all vehicles except bombers of 1-3 tiers and the coastal fleet.
        /// </summary>
        internal static string TheDatabaseContains {
            get {
                return ResourceManager.GetString("TheDatabaseContains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Torpedo count.
        /// </summary>
        internal static string TorpedoCount {
            get {
                return ResourceManager.GetString("TorpedoCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Torpedo speed.
        /// </summary>
        internal static string TorpedoSpeed {
            get {
                return ResourceManager.GetString("TorpedoSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Torpedo TNT.
        /// </summary>
        internal static string TorpedoTNT {
            get {
                return ResourceManager.GetString("TorpedoTNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Tower armor.
        /// </summary>
        internal static string TowerArmor {
            get {
                return ResourceManager.GetString("TowerArmor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Trivia game with War Thunder vehicles.
        /// </summary>
        internal static string TriviaGameWithWarThunderVehicles {
            get {
                return ResourceManager.GetString("TriviaGameWithWarThunderVehicles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Trivia game with World of Tanks vehicles.
        /// </summary>
        internal static string TriviaGameWithWorldOfTanksVehicles {
            get {
                return ResourceManager.GetString("TriviaGameWithWorldOfTanksVehicles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Try again.
        /// </summary>
        internal static string TryAgain {
            get {
                return ResourceManager.GetString("TryAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Try our apps:.
        /// </summary>
        internal static string TryOurApps {
            get {
                return ResourceManager.GetString("TryOurApps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Try our games:.
        /// </summary>
        internal static string TryOurGames {
            get {
                return ResourceManager.GetString("TryOurGames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Turn Time.
        /// </summary>
        internal static string TurnTime {
            get {
                return ResourceManager.GetString("TurnTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Turret armor.
        /// </summary>
        internal static string TurretArmor {
            get {
                return ResourceManager.GetString("TurretArmor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Type.
        /// </summary>
        internal static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Unguided missile.
        /// </summary>
        internal static string UnguidedMissile {
            get {
                return ResourceManager.GetString("UnguidedMissile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Update Database.
        /// </summary>
        internal static string UpdateDatabase {
            get {
                return ResourceManager.GetString("UpdateDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на FORCE UPDATE (Reboot is required).
        /// </summary>
        internal static string UPDATEReopenIsRequired {
            get {
                return ResourceManager.GetString("UPDATEReopenIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Upper armor plate.
        /// </summary>
        internal static string UpperArmorPlate {
            get {
                return ResourceManager.GetString("UpperArmorPlate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на USA.
        /// </summary>
        internal static string USA {
            get {
                return ResourceManager.GetString("USA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на USSR.
        /// </summary>
        internal static string USSR {
            get {
                return ResourceManager.GetString("USSR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Usual.
        /// </summary>
        internal static string Usual {
            get {
                return ResourceManager.GetString("Usual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Utility Helicopter.
        /// </summary>
        internal static string UtilityHelicopter {
            get {
                return ResourceManager.GetString("UtilityHelicopter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Vehicles per Nations.
        /// </summary>
        internal static string VehiclesPerNations {
            get {
                return ResourceManager.GetString("VehiclesPerNations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на War Thunder Quiz.
        /// </summary>
        internal static string WarThunderQuiz {
            get {
                return ResourceManager.GetString("WarThunderQuiz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Weight.
        /// </summary>
        internal static string Weight {
            get {
                return ResourceManager.GetString("Weight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на World of Tanks Quiz.
        /// </summary>
        internal static string WorldOfTanksQuiz {
            get {
                return ResourceManager.GetString("WorldOfTanksQuiz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Worse or equal.
        /// </summary>
        internal static string WorseOrEqual {
            get {
                return ResourceManager.GetString("WorseOrEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на WT Analyzer is an unofficial, must-have app for all War Thunder players. App uses own database with data collected from the game client and wiki.warthunder.com.
        /// </summary>
        internal static string WTAnalyzerAboutText {
            get {
                return ResourceManager.GetString("WTAnalyzerAboutText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на y.
        /// </summary>
        internal static string Y {
            get {
                return ResourceManager.GetString("Y", resourceCulture);
            }
        }
    }
}
